
export const LOG  =[
    {
      "id":496,
      'url':'assets/images/log3.png',
      'equi':'assets/images/rio.jpg',
  
    },
    {
      "id":498,
      'url':'assets/images/sporting.jpg',
      'equi':'assets/images/se.jpg',
    },
    {
        "id":503,
        'url':'assets/images/img-03.png',
        'equi':'assets/images/portoequipamento.jpg',
      },
      {
        "id":1903,
        'url':'assets/images/img-04.png',
        'equi':'assets/images/be.jpg',
      },
      {
        "id":5613,
        'url':'assets/images/braga.png',
        'equi':'assets/images/bee.jpg',
      },
      {
        "id":583,
        'url':'assets/images/log5.png',
        'equi':'assets/images/mor.jpg',
      },
      {
        "id":810,
        'url':'assets/images/log10.png',
        'equi':'assets/images/boa.png',
      },
      {
        "id":5575,
        'url':'assets/images/log13.png',
        'equi':'assets/images/mar.png',
      },
      {
        "id":1103,
        'url':'assets/images/log17.jpg',
        'equi':'assets/images/set.jpg',
      },
      {
        "id":1049,
        'url':'assets/images/log12.png',
        'equi':'assets/images/ton.png',
      },
      {
        "id":1103,
        'url':'assets/images/log17.png',
        'equi':'assets/images/chaves.jpgc',
      },
      {
        "id":1049,
        'url':'assets/images/log12.png',
        'equi':'assets/images/ton.png',
      },
      {
        "id":5529,
        'url':'assets/images/log4.png',
        'equi':'assets/images/na.jpg',
      },
      {
        "id":5530,
        'url':'assets/images/log8.png',
        'equi':'assets/images/san.jpg',
      },
      {
        "id":5543,
        'url':'assets/images/log11.png',
        'equi':'assets/images/gui.png',
      },
      {
        "id":5544,
        'url':'assets/images/log14.png',
        'equi':'assets/images/aves.jpg',
      },
      {
        "id":5565,
        'url':'assets/images/log7.png',
        'equi':'assets/images/fei.jpg',
      },
      {
        "id":5568,
        'url':'assets/images/log15.jpg',
        'equi':'assets/images/belem.png',
      },
      {
        "id":5601,
        'url':'assets/images/log2.png',
        'equi':'assets/images/por.jpg',
      },
      {
        "id":5620,
        'url':'assets/images/log9.png',
        'equi':'assets/images/set.jpg',
      },
      
      
      
      
  ]
 