
export const LOG  =[
    {
      "id":496,
      'url':'assets/images/log3.png',
      'equi':'assets/images/rio.jpg',
  
    },
    {
      "id":498,
      'url':'assets/images/sporting.jpg',
      'equi':'assets/images/se.jpg',
    },
    {
        "id":503,
        'url':'assets/images/img-03.png',
        'equi':'assets/images/portoequipamento.jpg',
      },
      {
        "id":1903,
        'url':'assets/images/img-04.png',
        'equi':'assets/images/be.jpg',
      },
      {
        "id":5613,
        'url':'assets/images/braga.png',
        'equi':'assets/images/bee.jpg',
      },
      {
        "id":583,
        'url':'assets/images/log5.png',
        'equi':'assets/images/mor.jpg',
      },
      {
        "id":810,
        'url':'assets/images/log10.png',
        'equi':'assets/images/boa.png',
      },
      {
        "id":5575,
        'url':'assets/images/log13.png',
        'equi':'assets/images/mar.png',
      },
      {
        "id":1103,
        'url':'assets/images/log17.jpg',
        'equi':'assets/images/set.jpg',
      },
      {
        "id":1049,
        'url':'assets/images/log12.png',
        'equi':'assets/images/ton.png',
      },
      {
        "id":1103,
        'url':'assets/images/log17.png',
        'equi':'assets/images/chaves.jpgc',
      },
      {
        "id":1049,
        'url':'assets/images/log12.png',
        'equi':'assets/images/ton.png',
      },
      {
        "id":5529,
        'url':'assets/images/log4.png',
        'equi':'assets/images/na.jpg',
      },
      {
        "id":5530,
        'url':'assets/images/log8.png',
        'equi':'assets/images/san.jpg',
      },
      {
        "id":5543,
        'url':'assets/images/log11.png',
        'equi':'assets/images/gui.png',
      },
      {
        "id":5544,
        'url':'assets/images/log14.png',
        'equi':'assets/images/aves.jpg',
      },
      {
        "id":5565,
        'url':'assets/images/log7.png',
        'equi':'assets/images/fei.jpg',
      },
      {
        "id":5568,
        'url':'assets/images/log15.jpg',
        'equi':'assets/images/belem.png',
      },
      {
        "id":5601,
        'url':'assets/images/log2.png',
        'equi':'assets/images/por.jpg',
      },
      {
        "id":5620,
        'url':'assets/images/log9.png',
        'equi':'assets/images/set.jpg',
      } ,{
        "id":2,
        'url':'assets/images/hof.png',
        'equi':'assets/images/hof1.jpg',
    
      },
      {
        "id":4,
        'url':'assets/images/dor.png',
        'equi':'assets/images/dor.jpg',
      },
      {
          "id":5,
          'url':'assets/images/bayern.png',
          'equi':'assets/images/ba.jpg',
        },
        {
          "id":6,
          'url':'assets/images/s.png',
          'equi':'assets/images/11.jpg',
        },
        {
          "id":64,
          'url':'assets/images/liver.png',
          'equi':'assets/images/dd.jpg',
        },
        {
          "id":65,
          'url':'assets/images/man.jpg',
          'equi':'assets/images/mane.jpg',
        },
        {
          "id":66,
          'url':'assets/images/logch1.png',
          'equi':'assets/images/ma.jpg',
        },
        {
          "id":73,
          'url':'assets/images/t.png',
          'equi':'assets/images/tot.jpg',
        },
        {
          "id":78,
          'url':'assets/images/atle.jpg',
          'equi':'assets/images/atletci.jpg',
        },
        {
          "id":81,
          'url':'assets/images/bar.jpg',
          'equi':'assets/images/baa.jpg',
        },
        {
          "id":95,
          'url':'assets/images/va.jpg',
          'equi':'assets/images/ver.jpg',
        },
        {
          "id":86,
          'url':'assets/images/real.png',
          'equi':'assets/images/re.jpg',
        },
        {
          "id":100,
          'url':'assets/images/r.jpg',
          'equi':'assets/images/rr.jpg',
        },
        {
          "id":108,
          'url':'assets/images/inter.png',
          'equi':'assets/images/int.jpg',
        },
        {
          "id":109,
          'url':'assets/images/juve.png',
          'equi':'assets/images/ju.jpg',
        },
        {
          "id":113,
          'url':'assets/images/na.png',
          'equi':'assets/images/ca.jpg',
        },
        {
          "id":503,
          'url':'assets/images/img-03.png',
          'equi':'assets/images/portoequipamento.jpg',
        },
        {
          "id":523,
          'url':'assets/images/lyon.png',
          'equi':'assets/images/ly.jpg',
        },
        {
          "id":524,
          'url':'assets/images/paris.png',
          'equi':'assets/images/ess.jpg',
        },
        {
          "id":548,
          'url':'assets/images/ãs.png',
          'equi':'assets/images/aq.jpg',
        },
        {
          "id":610,
          'url':'assets/images/paris.png',
          'equi':'assets/images/ess.jpg',
        },
        {
          "id":674,
          'url':'assets/images/psv.jpg',
          'equi':'assets/images/p.jpg',
        },
        {
          "id":678,
          'url':'assets/images/a.jpg',
          'equi':'assets/images/a1.jpg',
        },
        {
          "id":851,
          'url':'assets/images/cb.jpg',
          'equi':'assets/images/tt.jpg',
        },
        {
          "id":1871,
          'url':'assets/images/y.jpg',
          'equi':'assets/images/yy.jpg',
        },
        {
          "id":1887,
          'url':'assets/images/ss.png',
          'equi':'assets/images/sh.jpg',
        },
        {
          "id":1881,
          'url':'assets/images/p.png',
          'equi':'assets/images/pl.png',
        },
        {
          "id":1899,
          'url':'assets/images/psv.jpg',
          'equi':'assets/images/aee.jpg',
        },
        {
          "id":1890,
          'url':'assets/images/AEK.jpg',
          'equi':'assets/images/aee.jpg',
        },
        {
          "id":1903,
          'url':'assets/images/img-04.png',
          'equi':'assets/images/be.jpg',
        },
        {
          "id":5455,
          'url':'assets/images/lok.png',
          'equi':'assets/images/lok.jpg',
        },
        {
          "id":7283,
          'url':'assets/images/es.png',
          'equi':'assets/images/ww.jpg',
        },
        {
          "id":1900,
          'url':'assets/images/cs.png',
          'equi':'assets/images/waa.jpg',
        },
      
      
      
      
  ]
 